INSERT INTO tb_user (email, name, password, role, created_at) VALUES ('kaua@gmail.com', 'Kauã Almeida', '$2a$10$enPY3JfMQZEb3cF7mznk.OoQa7V0sq6uvSxnm7MlFclpD5JGVV6Nq', 'ADMIN', '2004-11-20 12:00:00');

INSERT INTO tb_course (name, degree, is_disabled) VALUES ('Mat A', 'INFANTIL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('Jardim A', 'INFANTIL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('Pré A', 'INFANTIL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('Mat F', 'INFANTIL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('Jardim F', 'INFANTIL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('Pré F', 'INFANTIL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('1º Ano A', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('2º Ano A', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('3º Ano A', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('4º Ano A', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('5º Ano A', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('6º Ano A', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('7º Ano A', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('8º Ano A', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('8º Ano B', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('9º Ano A', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('9º Ano B', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('1º Ano F', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('2º Ano F', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('3º Ano F', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('4º Ano F', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('5º Ano F', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('6º Ano F', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('7º Ano F', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('8º Ano F', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('9º Ano F', 'FUNDAMENTAL', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('1º Série A', 'MEDIO', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('2º Série A', 'MEDIO', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('3º Série A', 'MEDIO', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('1º Série B', 'MEDIO', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('2º Série B', 'MEDIO', 0);
INSERT INTO tb_course (name, degree, is_disabled) VALUES ('3º Série B', 'MEDIO', 0);

INSERT INTO tb_local (name, is_disabled) VALUES ('Sala Invertida', 0);
INSERT INTO tb_local (name, is_disabled) VALUES ('Laboratório 01', 0);
INSERT INTO tb_local (name, is_disabled) VALUES ('Lab. Tec. Ativas', 0);
INSERT INTO tb_local (name, is_disabled) VALUES ('Lab. Anatomia', 0);
INSERT INTO tb_local (name, is_disabled) VALUES ('Teatro', 0);
INSERT INTO tb_local (name, is_disabled) VALUES ('Auditório', 0);