INSERT INTO tb_user (email, name, password, role) VALUES ('kaua@gmail.com', 'Kauã Almeida', '$2a$10$enPY3JfMQZEb3cF7mznk.OoQa7V0sq6uvSxnm7MlFclpD5JGVV6Nq', 'ADMIN');

INSERT INTO tb_course (name, degree) VALUES ('Mat A', 'INFANTIL');
INSERT INTO tb_course (name, degree) VALUES ('Jardim A', 'INFANTIL');
INSERT INTO tb_course (name, degree) VALUES ('Pré A', 'INFANTIL');
INSERT INTO tb_course (name, degree) VALUES ('Mat F', 'INFANTIL');
INSERT INTO tb_course (name, degree) VALUES ('Jardim F', 'INFANTIL');
INSERT INTO tb_course (name, degree) VALUES ('Pré F', 'INFANTIL');
INSERT INTO tb_course (name, degree) VALUES ('1º Ano A', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('2º Ano A', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('3º Ano A', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('4º Ano A', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('5º Ano A', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('6º Ano A', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('7º Ano A', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('8º Ano A', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('8º Ano B', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('9º Ano A', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('9º Ano B', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('1º Ano F', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('2º Ano F', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('3º Ano F', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('4º Ano F', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('5º Ano F', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('6º Ano F', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('7º Ano F', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('8º Ano F', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('9º Ano F', 'FUNDAMENTAL');
INSERT INTO tb_course (name, degree) VALUES ('1º Série A', 'MEDIO');
INSERT INTO tb_course (name, degree) VALUES ('2º Série A', 'MEDIO');
INSERT INTO tb_course (name, degree) VALUES ('3º Série A', 'MEDIO');
INSERT INTO tb_course (name, degree) VALUES ('1º Série B', 'MEDIO');
INSERT INTO tb_course (name, degree) VALUES ('2º Série B', 'MEDIO');
INSERT INTO tb_course (name, degree) VALUES ('3º Série B', 'MEDIO');

INSERT INTO tb_local (name) VALUES ('Lab. de Ciências');
INSERT INTO tb_local (name) VALUES ('Sala Invertida');
INSERT INTO tb_local (name) VALUES ('Laboratório 01');
INSERT INTO tb_local (name) VALUES ('Lab. Tec. Ativas');
INSERT INTO tb_local (name) VALUES ('Lab. Anatomia');
INSERT INTO tb_local (name) VALUES ('Teatro');
INSERT INTO tb_local (name) VALUES ('Auditório');